# Generated by Django 5.1.7 on 2025-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250325_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Показувати', verbose_name='Головна'),
        ),
    ]
